# Generated by Django 5.0.6 on 2024-05-20 21:41

import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No name', max_length=100)),
                ('description', models.TextField(null=True)),
                ('avatar', models.ImageField(null=True, upload_to=tracker.models.board_avatar)),
                ('background', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No name', max_length=100)),
                ('description', models.TextField(null=True)),
                ('avatar', models.ImageField(null=True, upload_to=tracker.models.card_avatar)),
                ('background', models.CharField(max_length=100, null=True)),
                ('foreground', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No name', max_length=100)),
            ],
        ),
    ]
