# Generated by Django 5.0.6 on 2024-05-17 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='avatar',
            new_name='image',
        ),
    ]
