# Generated by Django 5.0.6 on 2024-05-17 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_rename_avatar_board_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='image',
            new_name='avatar',
        ),
    ]
