# Generated by Django 5.0.6 on 2024-05-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_rename_image_board_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='background',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='background',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
