# Generated by Django 5.0.6 on 2024-05-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_follower_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='permission',
            field=models.CharField(choices=[('Moderator', 'Moderator'), ('Reader', 'Reader')], default='Reader'),
        ),
    ]
