# Generated by Django 5.0.6 on 2024-05-20 00:59

import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_card_foreground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='avatar',
            field=models.ImageField(null=True, upload_to=tracker.models.board_avatar),
        ),
        migrations.AlterField(
            model_name='board',
            name='background',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='avatar',
            field=models.ImageField(null=True, upload_to=tracker.models.card_avatar),
        ),
        migrations.AlterField(
            model_name='card',
            name='background',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='foreground',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
