# Generated by Django 5.0.6 on 2024-05-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_board_avatar_alter_board_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(default='No name', max_length=100),
        ),
    ]
