# Generated by Django 5.0.6 on 2024-05-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_card_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(default='No name', max_length=100),
        ),
        migrations.AlterField(
            model_name='column',
            name='title',
            field=models.CharField(default='No name', max_length=100),
        ),
    ]
